name: weather_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^5.2.0
  mobx: ^0.3.8
  flutter_mobx: ^0.3.3
  http: ^0.12.0+4
  intl: ^0.16.1
  weather_icons: ^2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.3.1
  mobx_codegen: ^0.3.9


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
  fonts:
     - family: Gelasio
       fonts:
         - asset: fonts/Gelasio/Gelasio-Regular.ttf
         - asset: fonts/Gelasio/Gelasio-Italic.ttf
           style: italic
         - asset: fonts/Gelasio/Gelasio-Bold.ttf
           weight: 700
         - asset: fonts/Gelasio/Gelasio-SemiBold.ttf
           weight: 600
         - asset: fonts/Gelasio/Gelasio-Medium.ttf
           weight: 500
         - asset: fonts/Gelasio/Gelasio-BoldItalic.ttf
           weight: 700
           style: italic
         - asset: fonts/Gelasio/Gelasio-SemiBoldItalic.ttf
           weight: 600
           style: italic
         - asset: fonts/Gelasio/Gelasio-MediumItalic.ttf
           weight: 500
           style: italic           
     - family: Lora
       fonts:
         - asset: fonts/Lora/Lora-Regular.ttf
         - asset: fonts/Lora/Lora-Italic.ttf
           style: italic
         - asset: fonts/Lora/Lora-Bold.ttf
           weight: 700
         - asset: fonts/Lora/Lora-BoldItalic.ttf
           weight: 700
           style: italic
